### ISSUE TITLE
Null Reference Exception Error Adding Customer

### ISSUE THREAD

**Issue by mintile** [NCRCounterpointAPI/APITests#5]
I'm trying top use the POST example via Postman to add a customer. For my test I am only specifying a First Name and Last Name. My Post request looks liek this:

{
	"AR_CUST": {
		"FST_NAM": "Mike",
		"LST_NAM": "Intile"
	}
}

I see in the Form data section that it is asking for a workgroup. My workgroup is 1 and workgroup 1 has a next customer# specified. If I use 1 as the workgroup (without quotes) I get:

{
  "ErrorCode": "ERROR_UNKNOWN",
  "Message": "An error occurred during AddCustomer: Object reference not set to an instance of an object.,    at System.Object.GetType()\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SetFilter[T](IDbCommand dbCmd, String name, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SingleById[T](IDbCommand dbCmd, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_85.CustomerRepository_85.CPAPI.Repositories_85.ICustomerRepository.GetCustomerById(String custNo)\r\n   at CPAPI.Business_85.CustomerBusiness_85.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"
}

If I put the 1 in quotes I receive the following error:

{
  "ResponseStatus": {
    "ErrorCode": "NullReferenceException",
    "Message": "Object reference not set to an instance of an object.",
    "StackTrace": "   at lambda_method(Closure , AddCustomerRequest )\r\n   at ServiceStack.FluentValidation.Internal.Extensions.<>c__DisplayClass10_0`2.<CoerceToNonGeneric>b__0(Object x)\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at ServiceStack.FluentValidation.Validators.NotNullValidator.IsValid(PropertyValidatorContext context)\r\n   at ServiceStack.FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context)\r\n   at ServiceStack.FluentValidation.Internal.PropertyRule.<Validate>d__49.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at ServiceStack.FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)\r\n   at ServiceStack.Validation.ValidationFilters.RequestFilter(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)"
  }
}

**Comment by MikeRitchie** [comment]
Mike could you move this over to the "APIGuide" issues list? Sorry for the confusion, this one is in the wrong place. Here's the URL for the right one:
https://github.com/NCRCounterpointAPI/APIGuide/issues

**Comment by mintile** [comment]
Mike,

I was actually wrestling with which area to post it but I thought maybe the other thread was just for installation issues. I moved it.

Also, is there any documentation that would provide the minimum fields required to post new records for each endpoint? For example, my project will be importing data into counterpoint from a 3rd party eCommerce site. I need to create documents and also bring in credit card payment information. I’m working with Postman to familiarize myself with the environment and create some tests but my biggest struggle has been trying to determine what the required fields are for each POST endpoint. I was hoping that the tests that loaded from the API url would have sample data in the body but they don’t.


[cid:image003.png@01D2B2E4.0D34AFD0]Mike Intile
Retail Business Management Systems, Inc.
105 White Oak  Lane Old Bridge, NJ, 08857
40 Worth St. 10th Floor  New York, NY 10013
Phone: (732) 607-7773  Toll Free: (800) 506-4321  Fax: (732) 607-7755
mintile@rbms.com<mailto:mintile@rbms.com>  |  www.rbms.com<http://www.rbms.com/>
